version: "3.8"
services:
  mini-erp:
    build: .
    container_name: mini-erp
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - security-portal_default

networks:
  security-portal_default:
    external: true
